apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-app
  labels:
    app: incident-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: incident-app

  template:
    metadata:
      labels:
        app: incident-app

    spec:
      containers:
      - name: incident-app
        image: bandarurishitha/incident_app:latest

        ports:
        - containerPort: 5000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"